-- Deployed process versions, with the BPMN exactly as deployed.
CREATE TABLE mintwf_deployment (
    process_key  VARCHAR(255)                NOT NULL,
    version      INT                         NOT NULL,
    name         VARCHAR(1000),
    hash         CHAR(64)                    NOT NULL,
    xml          BLOB                        NOT NULL,
    deployed_at  TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    PRIMARY KEY (process_key, version)
);

-- One row per instance. doc holds the runtime state (tokens and variables) as JSON; the other columns are for
-- queries. revision is the optimistic lock.
CREATE TABLE mintwf_instance (
    seq              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id               VARCHAR(64)                 NOT NULL PRIMARY KEY,
    process_key      VARCHAR(255)                NOT NULL,
    process_version  INT                         NOT NULL,
    business_key     VARCHAR(255),
    status           VARCHAR(16)                 NOT NULL,
    started_at       TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    ended_at         TIMESTAMP(9) WITH TIME ZONE,
    revision         BIGINT                      NOT NULL,
    doc              CLOB                        NOT NULL
);

CREATE INDEX mintwf_instance_process ON mintwf_instance (process_key, status);

CREATE INDEX mintwf_instance_business_key ON mintwf_instance (business_key);

-- Pending jobs (retries > 0) and incidents (retries = 0).
CREATE TABLE mintwf_job (
    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id            VARCHAR(64)                 NOT NULL PRIMARY KEY,
    instance_id   VARCHAR(64)                 NOT NULL,
    execution_id  VARCHAR(64)                 NOT NULL,
    node_id       VARCHAR(255)                NOT NULL,
    type          VARCHAR(32)                 NOT NULL,
    due_at        TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    retries       INT                         NOT NULL,
    last_error    CLOB,
    failed_at     TIMESTAMP(9) WITH TIME ZONE,
    lock_owner    VARCHAR(255),
    lock_expiry   TIMESTAMP(9) WITH TIME ZONE,
    created_at    TIMESTAMP(9) WITH TIME ZONE NOT NULL
);

CREATE INDEX mintwf_job_due ON mintwf_job (retries, due_at);

CREATE INDEX mintwf_job_instance ON mintwf_job (instance_id);
