-- One row per visit of a token to a flow node. Rows are only inserted, apart from setting state and ended_at when the
-- token leaves. seq gives the order nodes were entered in.
CREATE TABLE mintwf_node_instance (
    seq           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id            VARCHAR(64)                 NOT NULL PRIMARY KEY,
    instance_id   VARCHAR(64)                 NOT NULL,
    execution_id  VARCHAR(64)                 NOT NULL,
    node_id       VARCHAR(255)                NOT NULL,
    node_type     VARCHAR(64)                 NOT NULL,
    state         VARCHAR(16)                 NOT NULL,
    started_at    TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    ended_at      TIMESTAMP(9) WITH TIME ZONE
);

CREATE INDEX mintwf_node_instance_instance ON mintwf_node_instance (instance_id, state);
